/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.salesforce.op.test;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class SparkExample extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SparkExample\",\"namespace\":\"com.salesforce.op.test\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"label\",\"type\":\"int\"},{\"name\":\"stuff\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"gender\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String id;
  @Deprecated public int label;
  @Deprecated public java.lang.String stuff;
  @Deprecated public java.lang.String gender;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public SparkExample() {}

  /**
   * All-args constructor.
   */
  public SparkExample(java.lang.String id, java.lang.Integer label, java.lang.String stuff, java.lang.String gender) {
    this.id = id;
    this.label = label;
    this.stuff = stuff;
    this.gender = gender;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return label;
    case 2: return stuff;
    case 3: return gender;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.String)value$; break;
    case 1: label = (java.lang.Integer)value$; break;
    case 2: stuff = (java.lang.String)value$; break;
    case 3: gender = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'label' field.
   */
  public java.lang.Integer getLabel() {
    return label;
  }

  /**
   * Sets the value of the 'label' field.
   * @param value the value to set.
   */
  public void setLabel(java.lang.Integer value) {
    this.label = value;
  }

  /**
   * Gets the value of the 'stuff' field.
   */
  public java.lang.String getStuff() {
    return stuff;
  }

  /**
   * Sets the value of the 'stuff' field.
   * @param value the value to set.
   */
  public void setStuff(java.lang.String value) {
    this.stuff = value;
  }

  /**
   * Gets the value of the 'gender' field.
   */
  public java.lang.String getGender() {
    return gender;
  }

  /**
   * Sets the value of the 'gender' field.
   * @param value the value to set.
   */
  public void setGender(java.lang.String value) {
    this.gender = value;
  }

  /** Creates a new SparkExample RecordBuilder */
  public static com.salesforce.op.test.SparkExample.Builder newBuilder() {
    return new com.salesforce.op.test.SparkExample.Builder();
  }
  
  /** Creates a new SparkExample RecordBuilder by copying an existing Builder */
  public static com.salesforce.op.test.SparkExample.Builder newBuilder(com.salesforce.op.test.SparkExample.Builder other) {
    return new com.salesforce.op.test.SparkExample.Builder(other);
  }
  
  /** Creates a new SparkExample RecordBuilder by copying an existing SparkExample instance */
  public static com.salesforce.op.test.SparkExample.Builder newBuilder(com.salesforce.op.test.SparkExample other) {
    return new com.salesforce.op.test.SparkExample.Builder(other);
  }
  
  /**
   * RecordBuilder for SparkExample instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SparkExample>
    implements org.apache.avro.data.RecordBuilder<SparkExample> {

    private java.lang.String id;
    private int label;
    private java.lang.String stuff;
    private java.lang.String gender;

    /** Creates a new Builder */
    private Builder() {
      super(com.salesforce.op.test.SparkExample.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.salesforce.op.test.SparkExample.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.label)) {
        this.label = data().deepCopy(fields()[1].schema(), other.label);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.stuff)) {
        this.stuff = data().deepCopy(fields()[2].schema(), other.stuff);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.gender)) {
        this.gender = data().deepCopy(fields()[3].schema(), other.gender);
        fieldSetFlags()[3] = true;
      }
    }
    
    /** Creates a Builder by copying an existing SparkExample instance */
    private Builder(com.salesforce.op.test.SparkExample other) {
            super(com.salesforce.op.test.SparkExample.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.label)) {
        this.label = data().deepCopy(fields()[1].schema(), other.label);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.stuff)) {
        this.stuff = data().deepCopy(fields()[2].schema(), other.stuff);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.gender)) {
        this.gender = data().deepCopy(fields()[3].schema(), other.gender);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.String getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public com.salesforce.op.test.SparkExample.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public com.salesforce.op.test.SparkExample.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'label' field */
    public java.lang.Integer getLabel() {
      return label;
    }
    
    /** Sets the value of the 'label' field */
    public com.salesforce.op.test.SparkExample.Builder setLabel(int value) {
      validate(fields()[1], value);
      this.label = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'label' field has been set */
    public boolean hasLabel() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'label' field */
    public com.salesforce.op.test.SparkExample.Builder clearLabel() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'stuff' field */
    public java.lang.String getStuff() {
      return stuff;
    }
    
    /** Sets the value of the 'stuff' field */
    public com.salesforce.op.test.SparkExample.Builder setStuff(java.lang.String value) {
      validate(fields()[2], value);
      this.stuff = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'stuff' field has been set */
    public boolean hasStuff() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'stuff' field */
    public com.salesforce.op.test.SparkExample.Builder clearStuff() {
      stuff = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'gender' field */
    public java.lang.String getGender() {
      return gender;
    }
    
    /** Sets the value of the 'gender' field */
    public com.salesforce.op.test.SparkExample.Builder setGender(java.lang.String value) {
      validate(fields()[3], value);
      this.gender = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'gender' field has been set */
    public boolean hasGender() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'gender' field */
    public com.salesforce.op.test.SparkExample.Builder clearGender() {
      gender = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public SparkExample build() {
      try {
        SparkExample record = new SparkExample();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.label = fieldSetFlags()[1] ? this.label : (java.lang.Integer) defaultValue(fields()[1]);
        record.stuff = fieldSetFlags()[2] ? this.stuff : (java.lang.String) defaultValue(fields()[2]);
        record.gender = fieldSetFlags()[3] ? this.gender : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
