/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.salesforce.op.test;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Gender { 
  Female, Male  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Gender\",\"namespace\":\"com.salesforce.op.test\",\"symbols\":[\"Female\",\"Male\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
